name: fetus_video_demo_py310
channels:
  - conda-forge
dependencies:
  - python=3.10
  - fastapi=0.116.1
  - uvicorn=0.35.0
  - sqlalchemy=2.0.41
  - pydantic-settings=2.10.1
  - numpy=2.2.6
  - opencv=4.10.0
  - python-multipart=0.0.20
